export const GET_ALL_DISHES = "GET_ALL_DISHES";
export const GET_ALL_DISHES_SUCCESS = "GET_ALL_DISHES_SUCCESS";
export const GET_ALL_DISHES_FAIL = "GET_ALL_DISHES_FAIL";

export const POST_NEW_DISH = "POST_NEW_DISH";
export const POST_NEW_DISH_SUCCESS = "POST_NEW_DISH_SUCCESS";
export const POST_NEW_DISH_FAIL = "POST_NEW_DISH_FAIL";

export const GET_DETAIL_DISH = "GET_DETAIL_DISH";
export const GET_DETAIL_DISH_SUCCESS = "GET_DETAIL_DISH_SUCCESS";
export const GET_DETAIL_DISH_FAIL = "GET_DETAIL_DISH_FAIL";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const RATING = "RATING";
export const RATING_SUCCESS = "RATING_SUCCESS";
export const RATING_FAIL = "RATING_FAIL";